version: "3"
services:
  web:
    image: metallic
    build: .
    ports:
      - "8080:8080"
      - "4433:4433"
      - "9229:9229" # debug port
    networks:
      - jpps
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOMAIN: "localhost"
      HTTP_PORT: "8080"
      HTTPS_PORT: "4433"
      USE_HTTPS: "false"
      SSL_KEY: "./certs/key.pem"
      SSL_CERT: "./certs/cert.pem"
    depends_on:
      - redis
    volumes:
      - '.:/app'
  redis:
    image: redis:6.2.6
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - jpps-redis:/data
    networks:
      - jpps

networks:
  jpps:
    external: false
    name: jpps

volumes:
  jpps-redis:
    driver: "local"